from __future__ import annotations

from pathlib import Path

from app.core.geometry import transformed_placement_polygon
from app.models.footprint import Footprint
from app.models.placement import Placement


DEFAULT_SAFE_Z = 5.0
DEFAULT_TRAVEL_FEED = 3000.0
DEFAULT_PLUNGE_FEED = 200.0
DEFAULT_CUT_FEED = 400.0
COORD_DIGITS = 4


def _fmt(value: float) -> str:
    text = f"{value:.{COORD_DIGITS}f}"
    text = text.rstrip("0").rstrip(".")
    if text == "-0":
        text = "0"
    return text


def _format_xy(x: float, y: float) -> str:
    return f"X{_fmt(x)} Y{_fmt(y)}"


def _polygon_contour_points(
    placement: Placement,
    footprint: Footprint,
) -> list[tuple[float, float]]:
    poly = transformed_placement_polygon(footprint, placement)

    if poly.is_empty:
        return []

    if not poly.is_valid:
        poly = poly.buffer(0)

    if poly.geom_type == "MultiPolygon":
        poly = max(poly.geoms, key=lambda geom: geom.area)

    coords = list(poly.exterior.coords)
    if len(coords) < 4:
        return []

    return [(float(x), float(y)) for x, y in coords]


def generate_contour_gcode(
    placements: list[Placement],
    footprints_by_id: dict[str, Footprint],
    cut_z: float,
    safe_z: float = DEFAULT_SAFE_Z,
    travel_feed: float = DEFAULT_TRAVEL_FEED,
    plunge_feed: float = DEFAULT_PLUNGE_FEED,
    cut_feed: float = DEFAULT_CUT_FEED,
    program_name: str = "PCB contour cut",
) -> str:
    """Generate simple absolute-position G-code for cutting every PCB contour.

    Assumptions:
    - project coordinates are machine XY coordinates, usually millimetres;
    - `cut_z` is the target cutting Z level, for example -1.6;
    - tool starts and ends at `safe_z`;
    - only exterior contours are exported, no pocketing and no drill holes.
    """
    if safe_z <= cut_z:
        raise ValueError("safe_z must be greater than cut_z.")
    if travel_feed <= 0 or plunge_feed <= 0 or cut_feed <= 0:
        raise ValueError("Feed rates must be greater than 0.")

    lines: list[str] = [
        f"; {program_name}",
        "; Generated by PCB Layout Optimizer",
        f"; Placements: {len(placements)}",
        f"; Cut Z: {_fmt(cut_z)}",
        f"; Safe Z: {_fmt(safe_z)}",
        "G21 ; units: millimetres",
        "G90 ; absolute coordinates",
        "G17 ; XY plane",
        "G94 ; feed per minute",
        f"G0 Z{_fmt(safe_z)} F{_fmt(travel_feed)}",
    ]

    for index, placement in enumerate(placements, start=1):
        footprint = footprints_by_id.get(placement.footprint_id)
        if footprint is None:
            raise ValueError(f"Unknown footprint id in placement: {placement.footprint_id}")

        points = _polygon_contour_points(placement, footprint)
        if not points:
            continue

        start_x, start_y = points[0]

        lines.extend(
            [
                "",
                f"; Board {index}: {placement.footprint_id}",
                f"G0 Z{_fmt(safe_z)}",
                f"G0 {_format_xy(start_x, start_y)} F{_fmt(travel_feed)}",
                f"G1 Z{_fmt(cut_z)} F{_fmt(plunge_feed)}",
            ]
        )

        for x, y in points[1:]:
            lines.append(f"G1 {_format_xy(x, y)} F{_fmt(cut_feed)}")

        # Ensure the contour is closed even if Shapely did not return an identical final point.
        end_x, end_y = points[-1]
        if abs(end_x - start_x) > 1e-9 or abs(end_y - start_y) > 1e-9:
            lines.append(f"G1 {_format_xy(start_x, start_y)} F{_fmt(cut_feed)}")

        lines.append(f"G0 Z{_fmt(safe_z)}")

    lines.extend(
        [
            "",
            f"G0 Z{_fmt(safe_z)}",
            "M30 ; end program",
            "",
        ]
    )

    return "\n".join(lines)


def save_contour_gcode(
    placements: list[Placement],
    footprints_by_id: dict[str, Footprint],
    output_path: str | Path,
    cut_z: float,
    safe_z: float = DEFAULT_SAFE_Z,
    travel_feed: float = DEFAULT_TRAVEL_FEED,
    plunge_feed: float = DEFAULT_PLUNGE_FEED,
    cut_feed: float = DEFAULT_CUT_FEED,
) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    gcode = generate_contour_gcode(
        placements=placements,
        footprints_by_id=footprints_by_id,
        cut_z=cut_z,
        safe_z=safe_z,
        travel_feed=travel_feed,
        plunge_feed=plunge_feed,
        cut_feed=cut_feed,
    )

    path.write_text(gcode, encoding="utf-8")
    return path
